// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZtTXl17YIuCTQwBtMoApsj3lV8Sxn8hQ',
    appId: '1:970626790015:web:aeb9896dce1a961ad3454a',
    messagingSenderId: '970626790015',
    projectId: 'flutter-lab-7ed22',
    authDomain: 'flutter-lab-7ed22.firebaseapp.com',
    storageBucket: 'flutter-lab-7ed22.firebasestorage.app',
    measurementId: 'G-8Y1RLTSYMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZWXOEgOnNZe2Aex8DIfKURDWxnl3J6s4',
    appId: '1:970626790015:android:5b6431206a018b5bd3454a',
    messagingSenderId: '970626790015',
    projectId: 'flutter-lab-7ed22',
    storageBucket: 'flutter-lab-7ed22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOo9T-fCMW1x0SKrDaPgpXaGxDbcVJPE',
    appId: '1:970626790015:ios:2c32b1692e2627c3d3454a',
    messagingSenderId: '970626790015',
    projectId: 'flutter-lab-7ed22',
    storageBucket: 'flutter-lab-7ed22.firebasestorage.app',
    iosBundleId: 'com.example.apiIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOo9T-fCMW1x0SKrDaPgpXaGxDbcVJPE',
    appId: '1:970626790015:ios:2c32b1692e2627c3d3454a',
    messagingSenderId: '970626790015',
    projectId: 'flutter-lab-7ed22',
    storageBucket: 'flutter-lab-7ed22.firebasestorage.app',
    iosBundleId: 'com.example.apiIntegration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZtTXl17YIuCTQwBtMoApsj3lV8Sxn8hQ',
    appId: '1:970626790015:web:5321692a65e5ad75d3454a',
    messagingSenderId: '970626790015',
    projectId: 'flutter-lab-7ed22',
    authDomain: 'flutter-lab-7ed22.firebaseapp.com',
    storageBucket: 'flutter-lab-7ed22.firebasestorage.app',
    measurementId: 'G-0ZLH1KDKEW',
  );
}
